name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install PHP dependencies
        run: composer install --no-dev --optimize-autoloader --no-progress

      - name: Install Node.js dependencies
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Create release package
        run: |
          mkdir -p dist
          rsync -av --exclude-from='.distignore' . dist/morden-backup/
          cd dist
          zip -r morden-backup-${{ github.ref_name }}.zip morden-backup/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/morden-backup-${{ github.ref_name }}.zip
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to WordPress.org
        if: startsWith(github.ref, 'refs/tags/v')
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
